"""LangGraph shared state definition."""

from typing import Annotated, Any
from typing_extensions import TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class GraphState(TypedDict):
    """Shared state passed between all LangGraph nodes.

    Fields
    ------
    messages : list[BaseMessage]
        Conversation history managed by the ``add_messages`` reducer.
    user_input : str
        Raw text the user sent in this turn.
    intent : str
        Classification produced by the router (PLAN | EXPLAIN | QUIZ | LOG_PROGRESS | REVIEW | LATEST).
    needs_rag : bool
        Whether RAG retrieval is required.
    needs_web : bool
        Whether web search is required.
    needs_db : bool
        Whether a database read is required.
    rag_context : str
        Retrieved document chunks (populated by retrieve_context tool).
    web_context : str
        Web search results (populated by web_search tool).
    db_context : dict[str, Any]
        Data fetched from PostgreSQL.
    last_intent : str | None
        Last resolved intent for this session.
    last_db_context : dict[str, Any] | None
        Cached DB context from the previous turn.
    sub_intent : str | None
        Optional sub-intent for DB planning.
    db_plan : list[dict[str, Any]]
        Action plan for DB operations.
    specialist_output : str
        Text produced by the specialist agent node.
    user_response : str
        User-facing response generated by a specialist (preferred over raw output).
    final_response : str
        Formatted response returned to the user.
    session_id : int | None
        Active session identifier for DB persistence.
    plan_draft : dict[str, Any] | None
        Draft study plan pending user confirmation.
    plan_confirmed : bool
        Whether the user has confirmed saving the draft plan.
    quiz_state : dict[str, Any] | None
        Cached quiz payload with questions and answer key for evaluation.
    quiz_results_saved : bool
        Prevents db→quiz loop after post-quiz save
    quiz_next_action : str | None
        Optional next node chosen by quiz agent (e.g., "db" or "format_response").
    """
    # Annotated fields allow us to apply the add_messages reducer to the messages field, 
    # so that all nodes receive the full conversation history without needing to manage it themselves.
    messages: Annotated[list[BaseMessage], add_messages]
    user_input: str
    intent: str
    needs_rag: bool
    needs_web: bool
    needs_db: bool
    rag_context: str
    web_context: str
    db_context: dict[str, Any]
    last_intent: str | None
    last_db_context: dict[str, Any] | None
    sub_intent: str | None
    db_plan: list[dict[str, Any]]
    specialist_output: str
    user_response: str
    final_response: str
    session_id: int | None
    plan_draft: dict[str, Any] | None
    plan_confirmed: bool
    quiz_state: dict[str, Any] | None
    quiz_results_saved: bool
    quiz_next_action: str | None
